# Defines a default set of lint rules enforced for
# projects at Google. For details and rationale,
# see https://github.com/dart-lang/pedantic#enabled-lints.
include: package:pedantic/analysis_options.yaml
# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
# Uncomment to specify additional rules.
linter:
  rules:
    # Always
    always_specify_types: true
    always_declare_return_types: true
    always_put_required_named_parameters_first: true
    always_use_package_imports: true

    # Avoid
    avoid_empty_else: true
    avoid_slow_async_io: true
    avoid_type_to_string: true
    avoid_returning_this: false
    avoid_shadowing_type_parameters: true
    avoid_relative_lib_imports: true
    avoid_returning_null_for_future: true
    avoid_types_as_parameter_names: true
    avoid_redundant_argument_values: true
    avoid_as: false
    avoid_init_to_null: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_classes_with_only_static_members: false
    avoid_double_and_int_checks: true
    avoid_field_initializers_in_const_classes: true
    avoid_function_literals_in_foreach_calls: true
    avoid_positional_boolean_parameters: true
    avoid_return_types_on_setters: true
    avoid_returning_null_for_void: true
    avoid_types_on_closure_parameters: true
    avoid_unnecessary_containers: true
    avoid_unused_constructor_parameters: true
    await_only_futures: true

    # Cancel
    cancel_subscriptions: true
    close_sinks: true

    # Prefer
    prefer_collection_literals: true
    prefer_conditional_assignment: true
    prefer_expression_function_bodies: true
    prefer_final_fields: true
    prefer_final_locals: true

    flutter_style_todos: true
    camel_case_extensions: true
    control_flow_in_finally: true
    hash_and_equals: true
    no_adjacent_strings_in_list: true
    no_duplicate_case_values: true
    no_logic_in_create_state: true
    prefer_relative_imports: false
    throw_in_finally: true
    unrelated_type_equality_checks: true
    use_key_in_widget_constructors: true
    annotate_overrides: true
    join_return_with_assignment: true
    no_default_cases: true

    sized_box_for_whitespace: true
    slash_for_doc_comments: true
    use_full_hex_values_for_flutter_colors: true

    omit_local_variable_types: false
    non_constant_identifier_names: true
    file_names: true
    empty_statements: true
    invariant_booleans: true
    unnecessary_this: true
    prefer_mixin: true


analyzer:
  enable-experiment:
    - spread-collections
  exclude: [build/**]