name: pictures_view
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: ^0.16.1
  http: 0.12.0+2
  logger: ^0.9.1

  redux: ^4.0.0
  rxdart: ^0.24.1
  redux_epics: ^0.14.0
  flutter_redux: ^0.6.0
  flutter_redux_navigation: ^0.6.0

  cached_network_image: 2.0.0

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: 3.2.5
  build_runner: 1.7.2

flutter:

  uses-material-design: true

  assets:
    - assets/gifs/loading_image.gif